### ISSUE TITLE
Why 3RScan dataset cannot be downloaded? 

### ISSUE THREAD

**Issue by shabiouyang** [OpenRobotLab/EmbodiedScan#38] opened 2024-04-15 08:34 UTC
### Model/Dataset/Scheduler description

Hi,

Thanks for your barvo work!

I'm trying to re-implemented your project for further reasearch, but I found I cannot access 3RScan dataset by their offical download link. Specfically, I'm using the script with "https://gist.github.com/WaldJohannaU/55f5e35992ea91157b789b15eac4d432", and no matter how we switch the vpn, we still cannot visit any data from "'http://campar.in.tum.de/public_datasets/3RScan/xxxx".

I don't know if anyone else has this problem. If so, would you mind sharing the 3RScan data set to Google Drive or Baidu cloud disk? This may allow more people to try your work.

Best regards,

### Open source status

- [ ] The model implementation is available
- [ ] The model weights are available.

**Comment by Tai-Wang** [comment] 2024-04-29 03:36
It seems the problem is not common and may be more suitable to be posted under 3RScan repo, so I temporarily close it.

**Closed by Tai-Wang** 2024-04-29 03:36 UTC
