### ISSUE TITLE
[Docs] How to test the demo?

### ISSUE THREAD

**Issue by yu3jun** [OpenRobotLab/EmbodiedScan#53] opened 2024-05-16 03:12 UTC
### Branch

main branch  https://mmdetection3d.readthedocs.io/en/latest/

### 📚 The doc issue

In your demo, config_path = '../config/detection/embodied-det3d_8xb1_embodiedscan-3d-284class-9dof-mlvl.py'
checkpoint_path = '../ckpt/continuous.pth' were used, however, I didn't find these two files in your repository.

I used 'configs/detection/mv-det3d_8xb4_embodiedscan-3d-284class-9dof.py' , 'mv-3ddet.pth' provided by you, and your simple dataset office to test demo.ipynb. but I can only get one picture of the results, the length of results in results = model.test_step(collate_data) is 1.

And then I used 'configs/detection/cont-det3d_8xb1_embodiedscan-3d-284class-9dof.py' , 'cont-3ddet.pth' provided by you, but it crashed in nms_filter function, hope you could give more detailed guidance about how to test your demo, thanks a lot !

**Comment by Elvis-tan** [comment] 2024-05-16 04:13
I replaced some places in demo.py, and now I can run the demo with 
'configs/detection/mv-det3d_8xb4_embodiedscan-3d-284class-9dof.py' , 'mv-3ddet.pth' .

for all `for i in range(len(results))` , I changed them to `for i in range(1, n_frames):`

Specifically ,
 `for i in range(len(results)):
    image_ann = info['images'][selected_image[i]]` 
was changed to 
`for i in range(1, len(selected_image)):
    image_ann = info['images'][selected_image[i]]`

Hope there will be a official response.

**Comment by mxh1999** [comment] 2024-05-16 09:06
The 'configs/detection/cont-det3d_8xb1_embodiedscan-3d-284class-9dof.py' and 'cont-3ddet.pth' you used are correct.
Could you please provide more information about the crash in nms_filter?

**Comment by Elvis-tan** [comment] 2024-05-17 02:50
> The 'configs/detection/cont-det3d_8xb1_embodiedscan-3d-284class-9dof.py' and 'cont-3ddet.pth' you used are correct. Could you please provide more information about the crash in nms_filter?

**As I mentioned above, I changed some places in your code, now I can run them without error, however, the output is not good as the original output in your demo.ipynb.**
 
**I used:**
`config_path = '../configs/detection/cont-det3d_8xb1_embodiedscan-3d-284class-9dof.py'`
`checkpoint_path = '../work_dirs/cont-3ddet/cont-3ddet.pth'`

**All I changed was as follows:** 

> for all `for i in range(len(results))` , I changed them to `for i in range(1, n_frames):`
> 
> Specifically , `for i in range(len(results)): image_ann = info['images'][selected_image[i]]` was changed to `for i in range(1, len(selected_image)): image_ann = info['images'][selected_image[i]]`
> 

**And some of my output are as follows:**
![image](https://github.com/OpenRobotLab/EmbodiedScan/assets/59783574/7d7dd19c-e0ca-4a90-af7a-f745dbb12948)
![image](https://github.com/OpenRobotLab/EmbodiedScan/assets/59783574/deed2c34-e9b6-4b37-89e8-0cb35aa7c326)
![image](https://github.com/OpenRobotLab/EmbodiedScan/assets/59783574/1a0ca969-1dd3-459a-9f3d-873eefb5aa65)

Hope you could give some advices, thanks a lot.

**Comment by mxh1999** [comment] 2024-05-17 04:40
From the places you changed, I understand that the `results` are not correct, even its length.
I can't reproduce this problem but i guess it may be due to incorrect inputs to the model.
[Here](https://drive.google.com/drive/folders/1KbFnWcleZXz1b-_SsCaGwy7MfNYcb4ix?usp=sharing) is the sample input and output. I hope this helps.
If you find the cause of this problem, please reply and let me know, thank you very much!

**Comment by mxh1999** [comment] 2024-05-23 12:11
> Does the demo in your repository only support 3d detection task for now? If not, then how could we test the capabilities of occupancy and visual grouding tasks in the wild? Thanks a lot for your answer.

Currently the demo only supports the 3d detection task, support for the occupancy and visual grouding tasks will be released after the CVPR 3D grounding challenge.

**Comment by Tai-Wang** [comment] 2024-08-19 02:28
We just support the occupancy visualization demo in #62  and the grounding one will be released with new methods and datasets.

**Closed by Tai-Wang** 2024-08-19 02:28 UTC

**Comment by chinagalaxy2002** [comment] 2024-12-12 03:28
> The 'configs/detection/cont-det3d_8xb1_embodiedscan-3d-284class-9dof.py' and 'cont-3ddet.pth' you used are correct.您使用的“configs/detection/cont-det3d_8xb1_embodiedscan-3d-284class-9dof.py”和“cont-3ddet.pth”是正确的。 Could you please provide more information about the crash in nms_filter?您能否提供有关 nms_filter 崩溃的更多信息？

![image](https://github.com/user-attachments/assets/7bbe9ec1-d71e-49cd-836b-0fc56d797e1f)

**Comment by chinagalaxy2002** [comment] 2024-12-12 03:29
> The 'configs/detection/cont-det3d_8xb1_embodiedscan-3d-284class-9dof.py' and 'cont-3ddet.pth' you used are correct.您使用的“configs/detection/cont-det3d_8xb1_embodiedscan-3d-284class-9dof.py”和“cont-3ddet.pth”是正确的。 Could you please provide more information about the crash in nms_filter?您能否提供有关 nms_filter 崩溃的更多信息？

这个崩溃信息我重试了很多遍，根据您提供的#40的解决方案仍然无法解决
